# Generated by Django 4.2.1 on 2023-05-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_miprueba_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='registar_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125)),
                ('apellidos', models.CharField(max_length=255)),
                ('pasaporte', models.CharField(max_length=255)),
                ('fecha_llegada', models.DateField(verbose_name='')),
                ('fecha_salida', models.DateField(verbose_name='')),
                ('cantidad_noches', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Miprueba',
        ),
    ]
