# Generated by Django 4.2.1 on 2023-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_registar_cliente_delete_miprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrar_gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_gasto', models.CharField(max_length=255)),
                ('importe', models.IntegerField(max_length=10)),
            ],
        ),
    ]
