# Generated by Django 4.2.1 on 2023-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_registrar_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registar_cliente',
            name='pais',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registar_cliente',
            name='cantidad_noches',
            field=models.IntegerField(),
        ),
    ]
